name: "Analyze Goat Protocol with Slither"

on: "workflow_call"

jobs:
  slither-analyze:
    runs-on: "ubuntu-latest"
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Run Slither analysis"
        uses: "crytic/slither-action@v0.3.1"
        id: "slither"
        with:
          fail-on: "none"
          sarif: "results.sarif"

      - name: "Upload SARIF file to GitHub code scanning"
        uses: "github/codeql-action/upload-sarif@v2"
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}

      - name: "Add summary"
        run: |
          echo "## Slither result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Uploaded to GitHub code scanning" >> $GITHUB_STEP_SUMMARY