name: Goat Protocol Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    strategy:
      fail-fast: true

    env:
      ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: PaulRBerg/foundry-multibuild@v1
        with:
          min: "0.8.20"
          max: "0.8.20"
          skip-test: "false"

      - name: "Run Goat Protocol Tests"
        run: 'forge test'